# Generated by Django 3.1.2 on 2020-10-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20201004_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_choice',
            field=models.CharField(choices=[('1', 'EVENT1'), ('2', 'EVENT2')], default='', max_length=1, null=True),
        ),
    ]
